### ISSUE TITLE
We should NOT output ComplexEvents which control other ComplexEvents

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#199]
The index card format now allows regulations to be two deep.

**Comment by myedibleenso** [comment]
Work on this is being done on the [`metaRegs`](https://github.com/clulab/reach/tree/metaRegs) branch.

@hickst, since you're the one who is most familiar with the export tentacles of our kraken, can you please finish off this issue by ensuring export can handle these sorts of Regulation Mentions (maybe it can already)?

Here is a summary of the subtasks involved in this issue:

- [X] Alter rules (Dane)
- [X] Fix cleanup action (Dane)
- [X] Add tests for Mentions (Dane)
- [X] Modify AssemblyManager to acknowledge Regs of Regs (of ...) (Gus)
- [X] Add AssemblyManager tests for Regs
- [ ] Ensure export can handle this (Tom)

**Comment by hickst** [comment]
Unfortunately, the FRIES output formatter cannot currently handle regulations with regulations as arguments. This seems to be because of the algorithm currently used, which makes a pass to generate, label, and cache all non-regulation events and a second pass to handle the regulation events. Until now, all arguments of events in the 2nd (regulation event) pass would already have been cached in the first pass and could just be referenced.

@MihaiSurdeanu Is there a simple modification to the current algorithm that will handle the 2-deep regulations?

**Comment by danebell** [comment]
@hickst I'm not super familiar with the code, but it looks like you could make the one loop for regulations into two loops. The conditional on the first one would change from 
```
if (REGULATION_EVENTS.contains(mention.label))
```
to 
```
if (REGULATION_EVENTS.contains(mention.label) && mention.arguments.getOrElse("controlled", Nil).exists(_.matches("SimpleEvent")))
```
And the second loop would have a similar thing except with the second constraint being negated like so:
```
if (REGULATION_EVENTS.contains(mention.label) && !mention.arguments.getOrElse("controlled", Nil).exists(_.matches("SimpleEvent")))
```

**Comment by hickst** [comment]
Thanks! I think I see....you are peeking down one level. This won't solve the nesting problem in general (i.e. if regulations can regulate events which can regulate events...) BUT maybe we don't need to if 2 levels is enough. This is cool and I will give it a try. Thanks again.

**Comment by danebell** [comment]
Well, if you want, you could create a tail-recursive function to handle just the regulations if you wanted to make it more general, but I doubt we'll go more than two regulations deep, because it's rare in practice (in my estimation) and likely to result in errors if we try to read it that way anyway.

**Comment by MihaiSurdeanu** [comment]
I'll take a look at the code soon.
Mihai

**Comment by hickst** [comment]
I think we've got it....just testing now.

**Comment by hickst** [comment]
Here's the FRIES JSON output from an NXML which contains the sentences:

```Akt inhibits the phosphorylation of AFT by BEF. The phosphorylation of AFT by BEF is inhibited by the ubiquitination of Akt.```

Would appreciate a review from anyone who has time:

[PMCissue199.uaz.events.json.txt](https://github.com/clulab/reach/files/309812/PMCissue199.uaz.events.json.txt)

**Comment by danebell** [comment]
That looks perfect to me, @hickst

**Comment by myedibleenso** [comment]
Looks like we're just missing tests: https://github.com/clulab/reach/blob/07e421edeb8b096b6f3389e6afeddb401ef7c465/src/test/scala/edu/arizona/sista/reach/TestFriesOutput.scala

**Comment by hickst** [comment]
MITRE changes mind: disallows this. Modify exporter to prevent complex events of complex events. Complex events can be controller but not controlled.

**Comment by hickst** [comment]
Hack to filter out ComplexEvent mentions which have a ComplexEvent as a controlled argument was added to the FRIES exporter on branch regCreg on 7/9/2016. That hack will be obviated by the resolution of issue #184

**Comment by myedibleenso** [comment]
>Complex events can be controller but not controlled.  

So a controller can be nested, but not the controlled?

**Comment by myedibleenso** [comment]
nm.  #184 says that we have to "flatten" the `controller`...
