### ISSUE TITLE
Automatic BRAT annotation configuration generation

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#20]
It would be great if Odin can output an annotation.conf file for brat with the events defined. That way we can customize the display properties like color, name, etc.

Here is a link to the specification:
http://brat.nlplab.org/configuration.html#advanced-relations

**Comment by myedibleenso** [comment]
It's my understanding that we can't easily do this.  Right, @hickst?

**Comment by hickst** [comment]
Where does Enrique want to use the config file? He didn't say but I suspect he wants to use the config file in the online Brat annotator server that he set up for the Biologists. That should be doable and a generator would be a handy tool to have.

The problem for the front end comes because you want to automatically send the new file to the front end and dynamically incorporate it into a running GUI. (Also, the front-end does not seem to recognize all the configuration options that the online server does, which could lead to some disappointment). This could still be a handy tool for building/packaging the front-end but I suspect that MS will view it as a low priority.

**Comment by enoriega** [comment]
I no longer need this. We can dismiss it.
