### ISSUE TITLE
Rule v. Action conflict

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#249]
With recent changes to processors, our parses have improved and a rule needed to be revised:

https://github.com/clulab/reach/blob/64f9926257e68177808a93d6e0a1af842ffa9b70/src/main/resources/org/clulab/reach/biogrammar/events/pos-reg_template.yml#L116

is now:

https://github.com/clulab/reach/blob/0874e10d67540fbe46481c8a47506b101c32054a/src/main/resources/org/clulab/reach/biogrammar/events/pos-reg_template.yml#L116

Unfortunately, this pattern conflicts with an old requirement that disallows syntactic overlap of arguments:

https://github.com/clulab/reach/blob/kbupdates/src/main/scala/org/clulab/reach/DarpaActions.scala#L137-L139

The requirement originates from this commit: https://github.com/clulab/reach/commit/57fe29fc

Anyway, the problem with all of this is that a test from `Feedback2` now fails:

https://github.com/clulab/reach/blob/64f9926257e68177808a93d6e0a1af842ffa9b70/src/test/scala/org/clulab/reach/TestFeedback2.scala#L21-30

@MihaiSurdeanu, do we need this old syntactic overlap filter?  

One argument against including this filter is that since the filter is hidden in the actions, it makes rules tricky to debug.  I propose we remove it, see what fails, and attempt to address those problems differently.

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: Yes, that constraint is very important. It filters out a lot of noise caused by false positives when one of the arguments is syntactically dominated by the other. Please do NOT take it out.

On the other hand, note that this just an apparent overlap. The two "prep_with" are actually different dependencies with the same name, caused by the CC in the text. So, theoretically, there is not overlap. But I understand why the action would pick it up as such.
Potential solutions:
1. Check for actual overlap of dependencies. That is, name+head+modifier must be the same to be an actual overlap.
2. Change the rule in question to a surface rule, e.g., "stimulated with" CONTROLLER .+ "analyzed for" CONTROLLED.

@myedibleenso: can you please attempt to fix this? I am overwhelmed with other things this week.

**Comment by myedibleenso** [comment]
It seems like it is following the the same dependency  (`3 prep_with 7`, leading from "stimulated" to "leptin"), no?

```
Tokens: (0,Cells,NNS), (1,were,VBD), (2,additionally,RB), (3,stimulated,VBN), (4,with,IN), (5,10,CD), (6,ng/ml,NN), (7,leptin,NN), (8,and,CC), (9,cell,NN), (10,extracts,NNS), (11,analyzed,VBN), (12,for,IN), (13,ErbB3,NN), (14,tyrosine,NN), (15,phosphorylation,NN), (16,.,.)

outgoing:
    3: (0,nsubjpass) (1,auxpass) (2,advmod) (7,prep_with) (10,prep_with)
    7: (5,num) (6,nn) (10,conj_and) (11,vmod)
    10: (9,nn)
    11: (15,prep_for)
    15: (13,nn) (14,nn)
```
Yes, I can "fix" it.  I just needed to know if that constraint was really all that important.  

Maybe there is a different solution to filter out that noise.  Do you know if there are any tests in place for that filter?  If so, I can take a look at a different fix for filtering out the junk...

If we can't alter the constraint, I guess 2 is the only option here that works, though it's the more brittle solution.
