### ISSUE TITLE
Phosphorylation event roles reversed

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#250]
From PMC534114, all these sentences are extracted as "EGF is phosphorylated". In all these sentences "X is phosphorylated in response to Y" is extracted as "Y is phosphorylated".

- "We first assayed the ability of the endogenous EGFR to be tyrosine autophosphorylated in response to EGF, as well as the ability of the exogenous ErbB3 receptor to be tyrosine phosphorylated in response to stimulation with either EGF or neuregulin (NRG).", 
- "Both Gab1 and Gab1 F446/472/589 are tyrosine phosphorylated in response to EGF treatment, and both form a stable complex with Shp2.", 
- "The endogenous EGFR is tyrosine phosphorylated in response to EGF in all cell lines.", 
- "We first assayed the cells for Gab1 expression, and for the ability of the mutant Gab1 F446/472/589 protein to become tyrosine phosphorylated in response to EGF treatment.", 
- "As shown in Figure, the endogenous Gab1 present in WT MEFs is tyrosine phosphorylated in response to EGF treatment.", 
- "Gab1 F627/659 becomes tyrosine phosphorylated in response to EGF treatment to levels approximately 1.5-fold higher than Gab1 as determined by densitometry, while Gab1 F446/472/589 / 627/659 does not show EGF induced tyrosine phosphorylation in this assay.", 
- "We first assayed the ability of the mutant Gab1 proteins to become tyrosine phosphorylated in response to EGF."

I'm working off the latest master and reading offline (not the web service).

**Comment by MihaiSurdeanu** [comment]
@bgyori: thanks! This is great feedback.

All: I created branch "issue250" to work on this, and I added 6 unit tests at the end of TestRegulationEvents. 

@myedibleenso, @danebell: can you please look at this?
Note that there are 2 issues here:
1. The test fails because we do not correctly identify the simple event: PROTEIN be phosphorylated. I suspect that this caused by a POS error ("phosphorylated" is tagged as JJ instead of VBN). We *do* have a regulation rule for "in response to" patterns, so this should work once the simple events are fine.
2. There is a false positive here "phosphorylated in response to PROTEIN" due to our old friend syntax_3_verb...
