### ISSUE TITLE
Problems with "X activates Y-induced Z"

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#332]
Hi, I've been looking over a bunch of sentences and I find that one common failure mode is with sentences of the form "X activates Y-induced Z." Often X and Y are genes/proteins/chemicals and Z is a biological process. 

For sentences like these, REACH often extracts "X activates Y". The  extraction "Y activates Z" is correct but possibly trivial; "X activates Z" is possibly justifiable though will be lacking critical context; the ideal would be a nested statement of the form "X activates (Y activates Z)".

Here are some examples:

From PMID25061982, yields "Thrombin activates NGF" (found by Positive_activation_syntax_1_verb):
```
Thrombin Enhances NGF Mediated Neurite Extension via Increased and Sustained Activation of p44/42 MAPK and p38 MAPK.
```

From PMID16189524, yields "Gefitinib activates Epidermal growth factor receptorvIII" (found by Positive_activation_syntax_2_verb):
```
Epidermal growth factor receptorvIII mediated cell proliferation and anchorage independent growth is both resistant and stimulated by gefitinib.
```

From PMID9763607, yields "Vitronectin activates HSP" (found by Positive_activation_token_1_verb):
```
In other epithelial cells including HeLa, another pathway depending on the serum factor vitronectin allows HSP dependent invasion.
```

From PMID25806093, yields "RARbeta activates retinoic acid", (found by Positive_activation_syntax_5_verb). Also note that the subject should be RARbeta2, not RARbeta, since these are RARbeta negative cells. You want something like "RARbeta2 activates growth inhibition" and/or "retinoic acid activates growth inhibition."
```
Indeed, expression of RARbeta2 in RARbeta negative lung cancer cells has been shown to restore retinoic acid induced growth inhibition [XREF_BIBR], and transgenic mice expressing antisense or other constructs that down-regulate RARbeta2 developed lung cancer [XREF_BIBR].
```

**Comment by MihaiSurdeanu** [comment]
Hi John,

We actually had this discussion with MITRE, which was caused by the fact that MITRE doesn't really accept nested statements. We proposed your solution for ""X activates Y-induced Z": "X activates (Y activates Z)", but they suggested we instead report two flat statements: "X activates Y" and "Y activates Z". What do you think? Should we discuss this at the next PI meeting, if biologically incorrect?

Some of the other errors reported here may be caused by incorrect syntax...

**Comment by johnbachman** [comment]
The two statement interpretation (X activates Y, Y activates Z) is not generally applicable. Consider "Ras mediates EGF activation of ERK." Very frequently papers report findings of this type, identifying mechanistic intermediates involved in an overall process. It doesn't make sense to put Ras upstream of EGF (Ras -> EGF, EGF-> ERK).

However, if Ras->ERK had been discovered first, you might find in in a paper: "EGF mediates Ras activation of ERK." (i.e., Ras activation of ERK occurs in the context of EGF stimulation.) In this case MITRE's interpretation actually works (EGF->Ras, Ras->ERK), but it's definitely not guaranteed to be the case. The "Y-mediated Z" part is generally what is already known; X is the new context being reported in the paper.

We don't have nested statements yet ourselves in INDRA, but we mean to add them in the very near future. I'm increasingly convinced that most of the cell biology literature actually reports findings of this type (identifying the additional context X required for Y to have an effect on Z). These types of findings are also where we can have the greatest incremental impact, since high throughput data collection is already pretty good at capturing binary interactions (X binds Y, X phosphorylates Y).

It's also worth noting that REACH often gets it in the way I suggested, returning "X activates Z." I just didn't report those examples. But here's one:

From PMID24126464, yields "ZVAD-fmk inactivates caspase-3." (found by Negative_activation_syntax_2_verb):

```Dasatinib induced caspase-3 activation is inhibited by zVAD-fmk.```

**Comment by johnbachman** [comment]
So yes, we should definitely discuss at the next PI meeting, as this will be important in future evaluations.

**Comment by johnbachman** [comment]
Here's another one I just came across (PMID21977288):

```The [mechanical] strain induced c-Fos expression can be reduced by PKC inhibition but not by PKA inhibition.```

REACH (correctly in my opinion) returns "PKC activates c-Fos." MITRE's interpretation would have "PKC activates strain." This is clearly nonsense as a standalone fact.

**Comment by MihaiSurdeanu** [comment]
I agree with you that a nested representation is best here, so I implemented it. We now correctly parse sentences such as:

Gab1 protein enhances EGF-induced activation of the PI-3
RAS1 activates AKT-induced apoptosis (pardon the fake biology here)
Indeed, expression of RARbeta2 has been shown to restore retinoic acid induced apoptosis

Some of the above examples still fail, due to other minor issues.
Also, please note that we had recursive representations for a while (they just didn't work in this case). For example, this sentence is parsed correctly (I believe):
"These results imply that Ack1 mediated Ras phosphorylation results in subsequent AKT activation."
Here we have Activation(Controller = Regulation(Ack1, Phosphorylation(Ras)), Controller = AKT)

**Comment by johnbachman** [comment]
Fantastic! We'll will make updates on our end accordingly.
