### ISSUE TITLE
"immunoprecipitated" a trigger for Binding? (from issue #321)

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#350]
@danebell, @myedibleenso: Why is the HSP20 example even creating a Binding? Is "immunoprecipitated" a trigger? If so, should we remove it?

[Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, (B and C) The empty vector transfected (lanes 1) and HSP20 overexpressing (lanes 2) HuH7 cell lysates were immunoprecipitated (IP) with antibodies for HSP20 (B) or normal rabbit IgG (C), followed by Western blotting (WB) using PI3K p85 antibodies, PI3K p110alpha antibodies, PI3K p110beta antibodies or HSP20 antibodies.),
 Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, The empty vector and HSP20 overexpressing HuH7 cell lysates were immunoprecipitated (IP) with antibodies for AKT, ERK, MEK and normal rabbit IgG followed by Western blotting (WB) using HSP20 antibodies (lanes 3 and 4).),
Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, (A) The empty vector transfected (lane 1) and HSP20 overexpressing (lane 2) HuH7 cell lysates were immunoprecipitated (IP) with antibodies for PI3K p85, PI3K p110alpha and PI3K p110beta subunits, followed by Western blotting (WB) using HSP20 antibodies.)]

**Comment by MihaiSurdeanu** [comment]
@johnbachman, @bgyori: is "immunoprecipitated" a valid trigger for Binding?

**Comment by bgyori** [comment]
It's tricky because immunoprecipitation is an experimental procedure done by a human, not something that happens inside the cell. Sometimes though, sentences talking about immunoprecipitation will provide evidence for the binding/interaction of two proteins. That's because the experiment tries to find things in a complex. So for instance the `immunoprecipitated (IP) with antibodies for PI3K` experiment will pull out PI3K and everything that happens to be bound to it. From that you can learn what PI3K interacts with.
But I would say, unless there is some sophisticated rule that tries to figure out what the sentence says about the interactions that the experiment provides evidence for, it should not be extracted.

**Comment by MihaiSurdeanu** [comment]
Thanks! @danebell: please remove it for now.

**Comment by johnbachman** [comment]
Certainly, none of the sentences that you list provide evidence for a binding interaction extraction--these presumably come from a figure legend where only the experimental procedure is described, not the outcome. However, one could very well find sentence where "immunoprecipitated" is used to specify binding interactions. For example, the abstract of one of the papers referenced, PMID 24223153 (http://www.ncbi.nlm.nih.gov/pubmed/24223153), contains the sentence: `HSP20 proteins in the HuH7 cells were coimmunoprecipitated with the p85 regulatory subunit and p110 catalytic subunit of phosphoinositide 3-kinase (PI3K), an upstream kinase of AKT.`

Here, "coimmunoprecipitated" would be a valid trigger for a binding event between HSP20 and either p85 or p110.

**Comment by danebell** [comment]
@johnbachman Is this true in general of "co(-)immunoprecipitated", as opposed to "immunoprecipitated"? If not, it doesn't seem that there's any linguistic basis for the the distinction, and we should just remove this trigger.
