### ISSUE TITLE
Keep the grounding info of BioMentions when using JSONSerializer

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#420]
[mentions.txt](https://github.com/clulab/reach/files/552169/mentions.txt)

Grounding information is not been kept when serializing to json. The code looks like it tries to but it doesn't make its way through the json object and the deserialization code doesn't attempt to load any existing info from the json string.

I also noticed that the serializer stores the complete document to which the mention belongs, which makes it yuge. I'll attach an example of a Seq[BioTextboundMention] serialized to json.

**Comment by myedibleenso** [comment]
Ah, I see what's happening.  You're not casting to `CorefMention`.  A `Mention` does not have grounding, though a `BioMention` does (I don't have an implicit class for `BioMention` right now).

A `CorefMention` has grounding info, along with a few other things.

Here's an example of the serialized grounding entry for a `CorefTextBoundMention`: https://gist.github.com/myedibleenso/8383af789b37ba598ff64ddd12c8b35b#file-corefmentions-json-L118-L124

```scala

import org.clulab.reach.mentions._
import org.clulab.reach.mentions.serialization.json._

// however you got these guys
val mentions: Seq[BioMention] = ???

val jsonString = mentions.map(_.toCorefMention)
  .filter(_ matches "Entity") // just to make the grounding a bit easier to see
  .json(pretty = true)

println(jsonString)
```

I will add a test for the grounding check and perhaps an implicit for BioMentions...

**Comment by myedibleenso** [comment]
>I also noticed that the serializer stores the complete document to which the mention belongs, which makes it yuge.

"Believe me, It's a tremendous size--the best size.  It will be yuge."

In order to deserialize a `Mention` from `json` (or anything), the `Document` to which it belongs must be available.  For convenience and practicality, the Documents referenced by the mentions in a  `Seq[Mention]` are also stored, but only once (ex. `mentions.json(pretty = false)`).  You can reduce the file size by setting `pretty = false`.  Getting the `json` for a single `Mention`, however, will not include the `Document`.  If you just wanted the `Mention` `json` and didn't care about deserializing them later (or want to store the documents some other way), you could do something like `val jsonString = Seq[String] = mentions.map(_.json(pretty = true)`.

**Comment by enoriega** [comment]
I see. Thanks for the clarification!

**Comment by enoriega** [comment]
I'm casting to BioMention, and that brings and empty Option[KBResulution]
