### ISSUE TITLE
Named entity prioritization issue

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#450]
We found that `DNA damage` which appears extremely often in the literature is cropped to `damage` and then grounded to MAGEE1 in UniProt. I would have expected `DNA damage` to appear as an entity that would be prioritized over `damage` as a longer match. The minimal example to reproduce this is the sentence: `DNA damage induces apoptosis`. @johnbachman might have other examples that include damage as a sub-string.

**Comment by hickst** [comment]
I think this should be in our Bio Process KB but what process should this be linked to? I'm looking at 
[cellular response to DNA damage stimulus](http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006974#term=info) as a good choice. Please let me know what you guys think:

**Comment by johnbachman** [comment]
We talked to @MihaiSurdeanu about this today. We often get events involving the entity text "damage" which, as @bgyori mentioned, gets grounded to MAGEE1. Depending on the corpus, this is *often* a truncation of "DNA damage", but not always--other forms of damage are sometimes mentioned.

I've attached a tab-separated file with 56 PMIDs/sentences that gave us extractions involving the entity "damage". Usually it's DNA damage but there's also "hepatic damage", "cellular damage", "mechanical damage", "LPS induced damage", etc.

Note: as an early shortcut for dealing with this, in the grounding map (in Bioentities) I explicitly mapped "damage" to the MeSH term D004249 (https://www.ncbi.nlm.nih.gov/mesh/?term=%22DNA+Damage%22%5BMeSH+Terms%5D), for "DNA damage". I should now change this to "DNA damage" so that the NER can pick up the full term and ground it correctly.

Strictly speaking, the GO term @hickst references isn't exactly synonymous, since it refers to the cellular *response* to the damage; however, I think that it's close enough (there isn't a GO term for the damage itself). So for grounding I would include both the GO term GO:0006974 and the MeSH term D004249.

[damage_sentences.txt](https://github.com/clulab/reach/files/593694/damage_sentences.txt)

**Comment by cl4yton** [comment]
A thought: these problematic examples sound like generally modifications to an existing groundable state or entity.  Should we consider "compound" grounding, where "damage" is grounded to a modifier, and associated with the entity/process?  (Are other cases similar?)

**Comment by hickst** [comment]
I agree with Clay: these all seem "stative"; much in the same way that "phosphorylated" or "activated" refer to different states of a (groundable) entity. Perhaps these could be represented in Reach as entities with state modifications attached?

**Comment by MihaiSurdeanu** [comment]
I think these grounding workarounds make sense.
But there might be also a NER bug here... The truncation from "DNA damage"
to "damage" should not happen, because we prefer longer entities in the
NER. I will look at this.

Mihai

**Comment by hickst** [comment]
@MihaiSurdeanu I added 'DNA damage' as a bio_process entry a couple days ago, so you should find that entry in the KB and in the ner files of the master (1.1.9-SNAPSHOT).

**Comment by MihaiSurdeanu** [comment]
This happened because "damage" is also a protein:
GROUNDING: KBResolution(damage, uniprot, Q9HCI5, homo sapiens)

@bgyori, @johnbachman: is this a valuable protein, or should we add "damage" to our stop-word list, i.e., words that are not tagged as entities when they appear in lower case?

**Comment by MihaiSurdeanu** [comment]
Ok, I propose the following:
1. @hickst: please add "damage" to our stop-word list. I think if it appears in lower case, it is highly unlikely to *not* be a protein. I think this term is highly ambiguous, and we should not tag as anything when in lower case.

2. @bgyori: in the file attached to this issue, I see other forms of this phrase:
"cell damage"
"cellular damage"
"ischemic damage"
"hepatic damage"
"oxidative damage"
"mucosal damage"
"genotoxic damage"
"myocardial damage"
"alkylation damage"
"vasculature damage"
"DNA methylation damage"
"excitotoxic damage"
"podocyte damage"
"cochlear damage"
"mitochondrial damage"
"renal damage"
Which of these, if any, should we map to the same biological process id as "DNA damage"?
I see that many of these are of the form: "$ORGAN damage" (e.g., "renal damage"). We can easily capture these with a Reach rule, since we already recognize organs. But: a) do you need these identified? b) what id do we map these to?
@hickst: can you please adjust our KBs based on Ben's response to point 2?

Thanks!

**Comment by johnbachman** [comment]
Of these, I would map only the following to DNA damage:

- genotoxic damage
- alkylation damage
- DNA methylation damage

**Comment by MihaiSurdeanu** [comment]
Thanks @johnbachman!
@hickst: can you please add the 3 entities above, to be mapped to the same id as "DNA damage"?
And then close this issue? Thanks!

**Comment by johnbachman** [comment]
Also one note--you mentioned that "damage" can also connote a protein (aka MAGEE1). I've never heard of this protein, but one way of making sure to get references to this protein would be to map only "DAMAGE" (all caps) to the protein, and not otherwise.

**Comment by johnbachman** [comment]
By the way, this appears to be the paper where the gene name "DAMAGE" was coined. May the authors be forever cursed for coming up with such a name...

https://www.ncbi.nlm.nih.gov/pubmed/14623885

**Comment by MihaiSurdeanu** [comment]
Agreed!

@hickst: it's safe then to add "damage" to stop word list. And the other 3 variants to be mapped to the same id as "DNA damage". Thanks!

**Comment by hickst** [comment]
@johnbachman Ha, you think that's bad....Uniprot has entries for genes with names '1' to '9'!!
For example, see: http://www.uniprot.org/uniprot/Q01016

**Comment by hickst** [comment]
Done: "damage" added to NER stop list, other 3 variants added to bio_processes KB (available in Bioresources 1.1.20-SNAPSHOT). Ran all Reach tests with version 1.1.20.
