### ISSUE TITLE
Bad prep_by attachment

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#47]
**Bug type**: `Bad parse`
```scala

import edu.arizona.sista.reach.nxml.FriesEntry
import edu.arizona.sista.reach.ReachSystem
import edu.arizona.sista.odin._

// Initialize the REACH system
val rs = new ReachSystem

def mentionsFromText(text:String):Seq[Mention]= {
  val entry = FriesEntry("test", "1", "example", "example", isTitle = false, text)
  rs.extractFrom(entry)
}

val sentenceText = "Inhibition of GSK3 by its specific inhibitor SB216763 or by overexpression of a dominant negative GSK3 attenuated the effect of STS"

val mentionText = "Inhibition of GSK3 by its specific inhibitor SB216763 or by overexpression of a dominant negative GSK3 attenuated the effect of STS."

val mentions = mentionsFromText(sentenceText)
```

**Comment by danebell** [comment]
Coreference isn't required for finding this Negative_activation. The wrong event that's captured is captured because of bad syntax. The parser thinks the 'by' means 'next to', so it's saying "GSK...attenuated...STS". Coreference doesn't find any antecedent for 'its', and it shouldn't as the system is currently designed, because 'its' is not an argument.

**Comment by myedibleenso** [comment]
Thanks for debugging, @danebell.  Can you change the tag on this one or open a new issue and close this one?  Maybe @MihaiSurdeanu can decide who it should be assigned to now?

**Comment by MihaiSurdeanu** [comment]
Closing this. Not sure how to handle bad syntax.
