### ISSUE TITLE
Grounding issues for unexpected labels

### ISSUE THREAD

**Issue by danebell** [clulab/reach#518]
I'm working with Ben Gyori and John Bachman to create some new labels (and accompanying rules), but the new entity types we create are not grounded. It would be fine if they received an AZ id, but they get no grounding at all. I can't see how this is happening. For example, in `taxonomy.yml`, we add a top line `- Domain`, and we additionally add a file `entities/domain.yml` containing:
```
- name: domaintest
  priority: 6
  action: mkBioMention
  type: token
  label: Domain
  pattern: |
    [word=palpatine & incoming=nn]
```

Then in the shell, we enter the sentence `Raf is a palpatine kinase.` `palpatine` is matched, but gets no grounding at all.

It seems to me that any entity should get _some_ grounding.

**Comment by hickst** [comment]
AFAIK, at present, Reach does not have the ability to arbitrarily add new labels. Grounding has been implemented, per MS' design, to recognize a limited and fixed set of labels, which are assigned to mentions by the NER before grounding is every called. Since the NER is based on a trained CRF, it is my understanding that adding new labels would require re-training the CRF which, in turn, would be dependant of having annotated training data available.

Whether every entity should get some grounding might depend on one's interpretation of what it means to be grounded. I think we have used grounding to mean that the entity is "recognized" in a  semantic domain and so we have additional information to associate with it. On the other hand...I think our default, UAZ grounding is just providing a "reference id" for an entity we wish to refer to and identify same instances of.

**Comment by hickst** [comment]
Having said that (previous comment), in `ReachEntityLookup.scala` any `BioTextBoundMention` whose label does not match one of the current fixed labels, should be given some grounding id:

https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/grounding/ReachEntityLookup.scala#L39-L56

**Comment by danebell** [comment]
@hickst The fact that some grounding id should be assigned is exactly what is confusing me. Somehow this isn't working as expected, since this entity never gets grounded.

In these cases (so far at least), we are trying to find limited set of entities recognized not through the NER but rather only through rules, similar to how mutations are recognized, so there is no need to alter the NER or bioresources. Since we apparently already intended to assign a UAZ grounding to every ungroundable entity, I don't think it's outside the scope of Reach to ensure that every entity does get UAZ grounding if no other.

**Comment by hickst** [comment]
It's important to understand that grounding is not the component which recognizes entities -- it is simply the component which assigns previously recognized biological entities an ID (when possible). 
If `palpatine` is really a biological noun phrase component, then you need to add it to the Bioresources KBs so that the NER will recognize it as such.

Note in the tested examples below that all NER-recognized biological entities are correctly given IDs by grounding.
```
Raf is a tyrosine kinase. // 2 grounded entities: Family & Site
Raf is a Antioxidant Response Element kinase.  // 2 grounded entities: Family & Cellular_component
Raf is a Vincristine kinase.  // 2 grounded entities: Family & Simple_chemical
Raf is a pancreatic vein kinase.  // 2 grounded entities: Family & Organ
Raf is a AMPKa1 kinase.  // 2 grounded entites: Family & Protein

```
