### ISSUE TITLE
Possible out-of-order error on the CMU output

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#629]
Manujinda from Clay and Adarsh's  group reported that there is a case in which the CMU output in which the lines are print out or oder.

I attach the example file in which the error occurs in case it is worth investigating.

[PMC4471258-cmu-out.txt](https://github.com/clulab/reach/files/3174151/PMC4471258-cmu-out.txt)

**Comment by kwalcock** [comment]
I just noticed this issue.  In the very latest update I made sure that it is a stable sort used in the output so that it is at least consistent.  Anything that was tied before will end up in the same place each time.  However, if the sorting was underspecified before and those things aren't really tied, there could be a problem.  The previous sort was by
```scala
.sortBy(r => (r.label, -r.docIDs.size, -r.seen))
```
and the new one just adds alphabetical order onto the end
```scala
.map { row => (row.label, -row.docIDs.size, -row.seen, row.toRow(cols, sep)) }
.sorted
```
If someone like @enoriega knows how it is supposed to be sorted, please let me know.

**Comment by MihaiSurdeanu** [comment]
I don't think this matters, as we are not promising any specific ordering.
