### ISSUE TITLE
Transcription_0 rule seems to be backwards

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#657]
After staring at this for a while, I'm starting to think that transcription_0 is accidentally implemented backwards, i.e.,
```
- name: transcription_0
  priority: ${ priority }
  example: "Indeed, expression of the Raf-RBD dramatically decreased Elk-1 dependent transcription by >80% whereas PI3KC2beta-RBD expressing cells were not inhibited further supporting the model that the PI3KC2beta-RBD does not interact with Ras-GTP."
  label: Transcription
  pattern: |
    trigger = [word=/(?i)transcription/ & tag=/^N/]
    theme:BioChemicalEntity = <dobj nsubj nmod_of? /conj_/*
    cause:BioChemicalEntity? = compound{1,2}
```
(note I'm using a slightly older version of the rule here before some of the edge types were replaced by variables, for clarity).

`cause` and `theme` should be flipped here. An example is "SRF induces TAZ transcription":
```
LEMMAS: srf induce taz transcription
roots: 1
outgoing:
	0:
	1: (0,nsubj) (3,dobj)
	2:
	3: (2,compound)
```
in which TAZ (supposed to be the theme) is a `compound` of the trigger, and SRF (supposed to be the cause) is a `<dobj nsubj` of the trigger. I can try to fix this and add a unit test.

**Comment by MihaiSurdeanu** [comment]
Yeah, I think you're right. Agree it's worth flipping.

This rule is subtle because it uses a `compound` dependency for cause, which is ambiguous. That is, if you see just "Elk-1 transcription" it's hard to say if Elk-1 is the cause or the theme. But, in this case, knowing that the cause is found somewhere else (at the end of the `<dobj nsubj` path), I think it's safe to flip.

**Comment by bgyori** [comment]
After having flipped the cause and theme, the next issue I'm running into is that two redundant events are extracted: `transcription_0 + toRelationMention` and `Positive_regulation_syntax_1_verb` both produce a positive regulation over the transcription event. Should / can something be done to eliminate this redundancy? 
```
EVENTS:   3

MENTION TEXT:  SRF induces TAZ transcription
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => transcription_0 + toRelationMention
	TYPE => CorefRelationMention
	------------------------------

	------------------------------
	controlled (List(Transcription, IncreaseAmount, Amount, SimpleEvent, Event, PossibleController)) => TAZ transcription
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => SRF
CONTEXT: NONE
	------------------------------



MENTION TEXT:  SRF induces TAZ transcription
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_1_verb
	TYPE => CorefEventMention
	------------------------------

	------------------------------
	TRIGGER => induces
	controlled (List(Transcription, IncreaseAmount, Amount, SimpleEvent, Event, PossibleController)) => TAZ transcription
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => SRF
CONTEXT: NONE
	------------------------------



MENTION TEXT:  TAZ transcription
LABELS:        List(Transcription, IncreaseAmount, Amount, SimpleEvent, Event, PossibleController)
DISPLAY LABEL: Transcription
	------------------------------
	RULE => transcription_0
	TYPE => CorefEventMention
	------------------------------

	------------------------------
	TRIGGER => transcription
	theme (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => TAZ
CONTEXT: NONE
	------------------------------
```
the first two

**Comment by MihaiSurdeanu** [comment]
Just a note that I’ve seen this and we’ll respond soon.


On March 7, 2020 at 6:00:38 PM, Benjamin M. Gyori (notifications@github.com)
wrote:

After having flipped the cause and theme, the next issue I'm running into
is that two redundant events are extracted: transcription_0 +
toRelationMention and Positive_regulation_syntax_1_verb both produce a
positive regulation over the transcription event. Should / can something be
done to eliminate this redundancy?

EVENTS:   3

MENTION TEXT:  SRF induces TAZ transcription
LABELS:        List(Positive_regulation, Regulation, ComplexEvent,
Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => transcription_0 + toRelationMention
	TYPE => CorefRelationMention
	------------------------------

	------------------------------
	controlled (List(Transcription, IncreaseAmount, Amount, SimpleEvent,
Event, PossibleController)) => TAZ transcription
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable,
BioChemicalEntity, BioEntity, Entity, PossibleController)) => SRF
CONTEXT: NONE
	------------------------------



MENTION TEXT:  SRF induces TAZ transcription
LABELS:        List(Positive_regulation, Regulation, ComplexEvent,
Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_1_verb
	TYPE => CorefEventMention
	------------------------------

	------------------------------
	TRIGGER => induces
	controlled (List(Transcription, IncreaseAmount, Amount, SimpleEvent,
Event, PossibleController)) => TAZ transcription
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable,
BioChemicalEntity, BioEntity, Entity, PossibleController)) => SRF
CONTEXT: NONE
	------------------------------



MENTION TEXT:  TAZ transcription
LABELS:        List(Transcription, IncreaseAmount, Amount,
SimpleEvent, Event, PossibleController)
DISPLAY LABEL: Transcription
	------------------------------
	RULE => transcription_0
	TYPE => CorefEventMention
	------------------------------

	------------------------------
	TRIGGER => transcription
	theme (List(Gene_or_gene_product, MacroMolecule, Equivalable,
BioChemicalEntity, BioEntity, Entity, PossibleController)) => TAZ
CONTEXT: NONE
	------------------------------

the first two

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/reach/issues/657?email_source=notifications&email_token=AAI75TXUJDUPEAIWOUDYHSLRGLU3LA5CNFSM4LDFO3Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOEJMCA#issuecomment-596153864>,
or unsubscribe

**Comment by MihaiSurdeanu** [comment]
I think I need some help here. @marcovzla, @myedibleenso, @danebell: did one of you wrote this method:
https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/darpa/MentionFilter.scala#L120

I think it needs to be extended to remove 1 of the regulations above. I think both rules are doing what they're supposed to, but the filterRegulations action is not detecting that two identical regulations are produced.

Can one of you please look at this method?
Thanks!

**Comment by danebell** [comment]
I think it was mostly me and @marcovzla. I'll see if I can work out what's going wrong.

**Comment by MihaiSurdeanu** [comment]
Thank you @danebell !

**Comment by MihaiSurdeanu** [comment]
@danebell : can you please look at this issue?

**Comment by MihaiSurdeanu** [comment]
The duplicated events issue was fixed by @danebell. The fix is now in master.
@bgyori: can you please check that you now have the expected output?
Thanks!
