### ISSUE TITLE
Crash due to a dynet error

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#685]
When running the latest system on a batch of documents, I got an error/crash that appears to be coming from dynet.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2b468da0b9, pid=305, tid=0x00007f2b476be700
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [dynet1264047638591502565.dll+0x12b0b9]  dynet::SimpleExecutionEngine::incremental_forward(unsigned int)+0x599
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /reach/hs_err_pid305.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./runReachCLI.sh: line 9:   305 Aborted                 sbt -J-Xmx16G 'run-main org.clulab.reach.RunReachCLI'
```
I haven't yet isolated the piece of text causing this but will post here if I find more info.

**Comment by MihaiSurdeanu** [comment]
Thanks!

Usually the bug is somewhere else... It shows up in dynet.

**Comment by MihaiSurdeanu** [comment]
Hey,
Did you manage to identify the text where this crash happens?
Thanks!

**Comment by bgyori** [comment]
No, I have a 300-document corpus that this crash happens with, but subdividing the corpus to try to identify a particular document has not worked so far, and I haven't had time to dig into this further.

**Comment by MihaiSurdeanu** [comment]
Maybe we can take over, if you send us these docs.


On May 12, 2020 at 7:21:26 AM, Benjamin M. Gyori (notifications@github.com)
wrote:

No, I have a 300-document corpus that this crash happens with, but
subdividing the corpus to try to identify a particular document has not
worked so far, and I haven't had time to dig into this further.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/reach/issues/685#issuecomment-627376608>, or
unsubscribe

**Comment by MihaiSurdeanu** [comment]
Fixed and merged.
