### ISSUE TITLE
API key for Elsevier

### ISSUE THREAD

**Issue by kingfish777** [clulab/reach#765]
Hi Ben,
How do you load the API key to connect to Elsevier, etc.? I was not able to satisfactorily answer this question from the documentation!
Thanks!
Scott

**Comment by bgyori** [comment]
Hi @kingfish777, not sure if this issue was meant for INDRA (https://github.com/sorgerlab/indra) which can be configured with API keys for Elsevier access? In any case, you can register here: https://dev.elsevier.com/ to get API access and then set your API key in the INDRA config file in ~/.config/indra/config.ini. Hope that works!

**Comment by kingfish777** [comment]
Excellent, yes that was what I meant. Thanks!
